import google from "../../assets/google.png"
import slack from "../../assets/slack.png"
import atlasian from "../../assets/atlasiane.png"
import dropbox from "../../assets/gdropbox.png"
import shopify from "../../assets/shopify.png"