import google from "../../assets/google.png"
import slack from "../../assets/slack.png"
import atlasian from "../../assetsatlasiane.png"
import dropbox from "../../assets/gdropboxpng"
import  from "../../assets/gong"