import google from "../../assets/google.png"
import slack from "../../assets/slack.png"
import atlasian from "../../assetsatlasiane.png"
import google from "../../assets/google.png"
import google from "../../assets/google.png"